name: Prettier for JS Code

on: [push, pull_request]

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@master
      with:
        fetch-depth: 1
    - name: Prettify the JS Code
      uses: creyD/prettier_action@master
      with:
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
